-- Phase 42 ADM: 002_task_columns.sql
-- Task 테이블 ALTER 모음 (Phase 4 ~ Phase 42.5)

ALTER TABLE Task ADD COLUMN deleted_at DATETIME;
ALTER TABLE Task ADD COLUMN assigned_agent TEXT DEFAULT NULL;
ALTER TABLE Task ADD COLUMN category TEXT DEFAULT 'QUICK_CHAT';
ALTER TABLE Task ADD COLUMN title TEXT DEFAULT '';
ALTER TABLE Task ADD COLUMN failure_count INTEGER DEFAULT 0;
ALTER TABLE Task ADD COLUMN project_task_num INTEGER DEFAULT NULL;
ALTER TABLE Task ADD COLUMN pipeline_step INTEGER DEFAULT NULL;
ALTER TABLE Task ADD COLUMN pipeline_is_review_stop INTEGER DEFAULT 0;
ALTER TABLE Task ADD COLUMN context_chain TEXT DEFAULT '[]';
ALTER TABLE Task ADD COLUMN priority TEXT DEFAULT 'medium';
ALTER TABLE Task ADD COLUMN has_artifact INTEGER DEFAULT 0;
ALTER TABLE Task ADD COLUMN artifact_url TEXT DEFAULT NULL;
ALTER TABLE Task ADD COLUMN project_id TEXT REFERENCES projects(id) ON DELETE SET NULL;
ALTER TABLE Task ADD COLUMN sprint_no INTEGER DEFAULT NULL;
